# Generated by Django 3.0.7 on 2020-11-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='draft', max_length=20, verbose_name='Order Status'),
        ),
    ]
